Repository campa-consortium/accelerator_simulation_codes, pull requests merged in 2021-05, with the labels that each got.

#25 Update FBPIC
  codes.json
Labels: help wanted

#27 Homepage: Filter Platform
  README.md
  codes.json
  index.html
Labels: enhancement

#28 MNT: Adding platform information for Astra, Bmad, IMPACT and Ocelot.
  codes.json
Labels: enhancement

#30 README: Python Example
  README.md
Labels: documentation
